### ISSUE TITLE
hmm...

### ISSUE THREAD

**Issue by beaups** [abazhaniuk/Publications#1]
Nice deck, unfortunately I didn't get to see the live presentation.  I'm a little confused by a few things (note my research referenced below is also done on SD810 devices):

    1.) HYP memory is writeable from EL1 (you have already discovered its readable).  Why resort to proxying HYP memory writes through SMC call when you can just directly write it?
    2.) Why plant rootkit in HYP at all?  You need EL1/kernel state to write HYP memory directly and/or use SMC instruction.  If you have EL1/kernel state already, why not just plant your rootkit there?

So I'm trying to understand the whole point of your presentation.  Your rootkit (presumably) does:
    EL1->SMC instruction->write HYP mem->install HYP rootkit->allow EL0 to read EL1 mem

Why not just do:
    EL1->install rootkit in EL1 memory (kernel module, code overwrite, etc)->allow EL0 to read EL1 mem

This whole thing reads like a humongous longcut, and I don't see any bug or unintended behavior in the first place.  Am I missing something?

Thanks!

--beaups

**Comment by abazhaniuk** [comment]
You right - it is possible. but I wanted to show that hypervisor is open in that systems and it is extra privilege level, which is allowing to install steal hypervisor rootkit. It is more like design issue in that systems.

**Comment by beaups** [comment]
Thanks for the response.  But, what is the extra privilege exactly?  On the affected platforms, it looks like intentional design to have EL1/EL2 share the same resources.  In fact, qcom didn't even bother to map a VMID (for XPU protection, etc) to EL2/HYP - it uses the same VMID (and as such, resource permissions) as EL1/APPS.  It just feels purely like intentional design to me, and was changed (as you noticed) significantly in newer SOC.

--beaups
